import type { MetadataRoute } from "next";
import { insightPosts, getInsightsPath, insightsBasePath } from "../src/data/insightsContent";
import { getPlatformPath, platformSlugs } from "../src/data/platformContent";
import type { Locale } from "../src/i18n";

const siteUrl = "https://varejo-investidor-site.vercel.app";

const staticPaths = [
  "/",
  "/pt",
  "/en",
  "/es",
  "/hi",
  "/ar",
  "/tr",
  "/id",
  "/vi",
  "/sinais",
  "/signals",
  "/calculadora-de-risco",
  "/relatorio-elite",
  "/elite-report",
  "/reporte-elite",
  "/elite-report-hi",
  "/educacao",
  "/servicos",
  "/services",
  "/sobre",
  "/about",
  "/formiga",
  "/lobo",
  "/harpia",
  "/forex",
  "/acoes",
  "/cripto",
  "/etfs",
  "/ouro",
  "/petroleo",
  "/commodities",
  "/fundos-imobiliarios",
  "/pt/forex",
  "/pt/acoes",
  "/pt/cripto",
  "/pt/etfs",
  "/pt/ouro",
  "/pt/petroleo",
  "/pt/commodities",
  "/pt/fundos-imobiliarios",
  "/en/forex",
  "/en/stocks",
  "/en/crypto",
  "/en/etfs",
  "/en/gold",
  "/en/oil",
  "/en/commodities",
  "/es/forex",
  "/es/acciones",
  "/es/cripto",
  "/es/etfs",
  "/es/oro",
  "/es/petroleo",
  "/es/commodities",
  "/hi/forex",
  "/hi/stocks",
  "/hi/crypto",
  "/hi/etfs",
  "/hi/gold",
  "/hi/oil",
  "/hi/commodities",
  "/ar/forex",
  "/ar/stocks",
  "/ar/crypto",
  "/ar/etfs",
  "/ar/gold",
  "/ar/oil",
  "/ar/commodities",
  "/ar/elite-report",
  "/tr/forex",
  "/tr/stocks",
  "/tr/crypto",
  "/tr/etfs",
  "/tr/gold",
  "/tr/oil",
  "/tr/commodities",
  "/tr/elite-report",
  "/id/education",
  "/id/signals",
  "/id/elite-report",
  "/id/services",
  "/id/about",
  "/id/formiga",
  "/id/lobo",
  "/id/harpia",
  "/id/forex",
  "/id/stocks",
  "/id/crypto",
  "/id/etfs",
  "/id/gold",
  "/id/oil",
  "/id/commodities",
  "/vi/education",
  "/vi/signals",
  "/vi/elite-report",
  "/vi/services",
  "/vi/about",
  "/vi/formiga",
  "/vi/lobo",
  "/vi/harpia",
  "/vi/forex",
  "/vi/stocks",
  "/vi/crypto",
  "/vi/etfs",
  "/vi/gold",
  "/vi/oil",
  "/vi/commodities",
  ...Object.values(insightsBasePath),
];

const sitemapLocales: Locale[] = ["pt", "en", "es", "hi", "ar", "tr", "id", "vi"];

export default function sitemap(): MetadataRoute.Sitemap {
  const staticEntries = staticPaths.map((path) => ({
    url: `${siteUrl}${path}`,
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: path === "/" ? 1 : 0.8,
  }));

  const insightEntries = insightPosts.map((post) => ({
    url: `${siteUrl}${getInsightsPath(post.locale, post.slug)}`,
    lastModified: new Date(post.date),
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  const platformEntries = sitemapLocales.flatMap((locale) =>
    platformSlugs.map((slug) => ({
      url: `${siteUrl}${getPlatformPath(locale, slug)}`,
      lastModified: new Date(),
      changeFrequency: "monthly" as const,
      priority: 0.72,
    })),
  );

  return [...staticEntries, ...insightEntries, ...platformEntries];
}
