import type { MetadataRoute } from "next";
import { insightPosts, getInsightsPath, insightsBasePath } from "../src/data/insightsContent";

const siteUrl = "https://varejo-investidor-site.vercel.app";

const staticPaths = [
  "/",
  "/pt",
  "/en",
  "/es",
  "/hi",
  "/ar",
  "/tr",
  "/sinais",
  "/signals",
  "/educacao",
  "/servicos",
  "/services",
  "/sobre",
  "/about",
  "/formiga",
  "/lobo",
  "/harpia",
  "/forex",
  "/acoes",
  "/cripto",
  "/etfs",
  "/ouro",
  "/petroleo",
  "/commodities",
  "/fundos-imobiliarios",
  "/pt/forex",
  "/pt/acoes",
  "/pt/cripto",
  "/pt/etfs",
  "/pt/ouro",
  "/pt/petroleo",
  "/pt/commodities",
  "/pt/fundos-imobiliarios",
  "/en/forex",
  "/en/stocks",
  "/en/crypto",
  "/en/etfs",
  "/en/gold",
  "/en/oil",
  "/en/commodities",
  "/es/forex",
  "/es/acciones",
  "/es/cripto",
  "/es/etfs",
  "/es/oro",
  "/es/petroleo",
  "/es/commodities",
  "/hi/forex",
  "/hi/stocks",
  "/hi/crypto",
  "/hi/etfs",
  "/hi/gold",
  "/hi/oil",
  "/hi/commodities",
  "/ar/forex",
  "/ar/stocks",
  "/ar/crypto",
  "/ar/etfs",
  "/ar/gold",
  "/ar/oil",
  "/ar/commodities",
  "/tr/forex",
  "/tr/stocks",
  "/tr/crypto",
  "/tr/etfs",
  "/tr/gold",
  "/tr/oil",
  "/tr/commodities",
  ...Object.values(insightsBasePath),
];

export default function sitemap(): MetadataRoute.Sitemap {
  const staticEntries = staticPaths.map((path) => ({
    url: `${siteUrl}${path}`,
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: path === "/" ? 1 : 0.8,
  }));

  const insightEntries = insightPosts.map((post) => ({
    url: `${siteUrl}${getInsightsPath(post.locale, post.slug)}`,
    lastModified: new Date(post.date),
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  return [...staticEntries, ...insightEntries];
}
